INSERT INTO images_tb (mood, content) VALUES ('confused', '/assets/images/confused1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('confused', '/assets/images/confused2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('angry','/assets/images/angry1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('angry','/assets/images/angry2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('happy','/assets/images/happy1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('happy','/assets/images/happy2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('sad','/assets/images/sad1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('sad','/assets/images/sad2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('sad','/assets/images/sad3.jpg');
INSERT INTO images_tb (mood, content) VALUES ('inlove','/assets/images/inlove1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('inlove','/assets/images/inlove2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('sassy','/assets/images/sassy1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('sassy','/assets/images/sassy2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('sassy','/assets/images/sassy3.jpg');
INSERT INTO images_tb (mood, content) VALUES ('overit','/assets/images/overit1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('overit','/assets/images/overit2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('excited','/assets/images/excited1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('excited','/assets/images/excited2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('exhausted','/assets/images/exhausted1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('exhausted','/assets/images/exhausted2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('coding','/assets/images/coding1.jpg');
INSERT INTO images_tb (mood, content) VALUES ('coding','/assets/images/coding2.jpg');
INSERT INTO images_tb (mood, content) VALUES ('coding','/assets/images/coding3.jpg');